public/members.json
adding my website to the webring
=> Adrian Lobo

public/members.json
<s>P.S. Don't mind the ugly website background, that's temporarily broken I'll fix it today or tomorrow</s>
Fixed
=> Add Khushraj Rathod

public/members.json
=> Added my name ^_^ & Remove Fayd

public/members.json
=> removed my webring

public/members.json
#39 this should do it, there was a discrepancy between the url given and his site with www
=> fix John Lins url

members.json
My domain expired, so I plan to redeploy my website sometime in the near future. In the meantime, I am withdrawing from the webring
=> Remove myself

index.html, public/style.css
hack club flag logo made responsive. my previous PR made some responsive error. now it's solved.
=> waving flag responsive

members.json
Hope this is what I was supposed to do.
=> Added myself to webring!

members.json
=> Fixed with new domain name

members.json
I have graducated from high school
=> Remove Rafael Cenzano

members.json
Added my personal site to hackclub webring !!
=> added my site , yoohoo !!

members.json
www.laker.gay -> www.laker.tech
=> fixing my website link :)

scripts/package.json, scripts/yarn.lock
=> Revert "Bump node-fetch from 2.6.1 to 3.1.1 in /scripts"

members.json
I edited the wrong file in my initial PR ( #71 ), so I'm making a new one.
=> Join the webring for real

members.json
https://cytronicoder.com
(It might not be updated right now, as I am running a dev build...)
=> Add my website into the webring

public/index.html, public/script.js, public/style.css
1. Fixed #153 
2. Fixed Color Contrast and fixed css
=> Fixed security issue & link (color contrast)

members.json
=> new url for my website

members.json
I am no longer participating in the Hack Club webring
=> Remove Reese Armstrong

members.json
My website should also now have the webring
=> I added my name and website url to the json

members.json
I would like to be added to the hack club web ring, you can verify I'm in the slack by looking for @Kokonico (or KKNC) within it.
=> Add Kokonico to members.json

members.json
Hi! I added my website to the webring, please merge it!
=> Add viruus.zip to the webring!

members.json
Add my site to webring. 
Merges https://github.com/NeonGamerBot-QK/hackclub-nest/pull/1
=> feat: add me

members.json
My slack handle is roguewielder
=> Requesting permission to join.

members.json
=> fix member.json formatting

members.json
=> got a new domain

members.json
Hey @sampoder i deleted all old use and non active users
=> Deleted Duplicate and non - active sites

members.json
https://hexaa.sh/ yes
(info: currently, the web still hasn't finished.)
old pull-requests #200
=> feat: add hexaa

members.json
=> Add mostypc123

members.json
=> PR: webring appl again

members.json
Reverts hackclub/webring#215
Hey Alex 
reverting it as need to change something in repo. can you please make pull again
=> Revert "Update members.json"

members.json
hi hi! I have added the webring links to my site!!!!
=> Add noololly's site

members.json
Hello! I had this from about 5 or 6 years ago, and I no longer maintain the site it connects to. Just removing my name from the list.
=> remove website

members.json
Adding my user and WIP website to the ring
=> Update members.json with ThePangel (mee)

members.json
made a new website and added the webring
website:
https://spacevini8.n0budget.com/
=> added my website to the members.json

members.json
Below is a screenshot of the #lounge channel on the Slack, with the profile flyout open if you need to prove that I am in the Slack.
=> Adding my website to the webring

members.json
Should have added myself a while ago
=> add virtualfuzz to webring

members.json
=> Add arcaege.dev to members.json
